M48
; DRILL file {KiCad (7.0.0)} date Tue May  2 23:46:44 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-02T23:46:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T2
X259.775Y40.7
T3
X2.625Y40.33
X2.625Y15.82
X49.575Y40.33
X49.575Y15.82
T1
G00X264.175Y40.95
M15
G01X264.175Y40.45
M16
G05
T0
M30
